'use client';

import React from 'react';
import { X, Printer, Download, CheckCircle2, Shield, Train, FileText } from 'lucide-react';
import { IntegratedJointBlock, OptimizedAssignment } from '../../types/railway';

interface BlockBulletinModalProps {
  isOpen: boolean;
  onClose: () => void;
  jointBlocks: IntegratedJointBlock[];
  assignments: OptimizedAssignment[];
}

export const BlockBulletinModal: React.FC<BlockBulletinModalProps> = ({
  isOpen,
  onClose,
  jointBlocks,
  assignments,
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-2xs animate-in fade-in overflow-y-auto">
      <div className="w-full max-w-3xl bg-white rounded-2xl shadow-2xl border border-slate-300 flex flex-col max-h-[90vh] animate-in zoom-in-95 duration-200">
        {/* Header Bar */}
        <div className="p-4 border-b border-slate-200 bg-slate-50 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-slate-900 text-white">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-950">
                Official Indian Railways Block Bulletin Preview
              </h3>
              <p className="text-xs text-slate-500">
                Operating Order No. NR/DLI/OPT/BB-2026/W36-01
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => window.print()}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white border border-slate-300 text-xs font-semibold text-slate-700 hover:bg-slate-50 cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Bulletin</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-200 cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Document Paper View */}
        <div className="p-6 overflow-y-auto space-y-6 bg-white text-slate-900 font-sans text-xs">
          {/* Official IR Letterhead */}
          <div className="text-center space-y-1 pb-4 border-b-2 border-slate-900">
            <div className="font-serif font-black text-sm uppercase tracking-wider text-slate-950">
              NORTHERN RAILWAY — DELHI DIVISION
            </div>
            <div className="font-semibold text-xs text-slate-700">
              OFFICE OF THE SENIOR DIVISIONAL OPERATIONS MANAGER (SR. DOM)
            </div>
            <div className="text-[11px] font-mono text-slate-600">
              CONTROL OFFICE APPLICATION (COA) &amp; BLOCKSYNC ENGINE MEMORANDUM
            </div>
            <div className="pt-2 flex justify-between text-[11px] font-mono text-slate-600">
              <span>Ref: NR/DLI/BB/2026-36/FINAL</span>
              <span>Dated: 30-AUG-2026 19:15 IST</span>
            </div>
          </div>

          {/* Subject Line */}
          <div className="p-2.5 rounded bg-slate-100 font-semibold text-slate-900 leading-snug">
            SUBJECT: Sanction of Coordinated Engineering, S&amp;T, and TRD/OHE Maintenance Blocks for Week 36 (31.08.2026 to 06.09.2026) on Delhi–Ghaziabad–Aligarh–Tundla–Kanpur Section.
          </div>

          {/* Executive Summary */}
          <div className="space-y-1.5 text-slate-800">
            <p>
              1. In accordance with the optimized plan generated by the <strong>BlockSync CP-SAT Engine</strong>, approval is hereby accorded for the execution of high-priority defect rectifications, with mandatory observance of safety rules.
            </p>
            <p>
              2. <strong>Integrated Joint Block Protocols:</strong> Wherever Track and OHE works are combined, traction power isolation shall be confirmed 15 minutes prior to track gang entry.
            </p>
          </div>

          {/* Approved Joint Blocks Table */}
          <div className="space-y-2">
            <h4 className="font-bold text-slate-950 uppercase tracking-wider text-[11px] flex items-center gap-1.5">
              <span>Table A: Approved Integrated Joint Blocks (Track + OHE Power Co-Utilization)</span>
            </h4>
            <div className="border border-slate-300 rounded-lg overflow-hidden">
              <table className="w-full text-left border-collapse text-[11px]">
                <thead className="bg-slate-100 border-b border-slate-300 font-bold text-slate-800">
                  <tr>
                    <th className="p-2 border-r border-slate-300">JB #</th>
                    <th className="p-2 border-r border-slate-300">Corridor Track Section</th>
                    <th className="p-2 border-r border-slate-300">Sanctioned Time</th>
                    <th className="p-2 border-r border-slate-300">Merged Depts</th>
                    <th className="p-2 border-r border-slate-300">Power Isolation Permit</th>
                    <th className="p-2">Downtime Saved</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-200">
                  {jointBlocks.map((jb) => (
                    <tr key={jb.id} className="hover:bg-slate-50">
                      <td className="p-2 font-bold font-mono border-r border-slate-200">
                        #JB-0{jb.jointBlockNumber}
                      </td>
                      <td className="p-2 font-medium border-r border-slate-200">
                        {jb.corridorName}
                      </td>
                      <td className="p-2 font-mono border-r border-slate-200">
                        {jb.workWindowTime}
                      </td>
                      <td className="p-2 border-r border-slate-200">
                        <span className="font-semibold text-orange-900">Track</span> +{' '}
                        <span className="font-semibold text-amber-900">OHE</span>
                      </td>
                      <td className="p-2 font-mono text-[10px] border-r border-slate-200">
                        {jb.powerIsolationTime}
                      </td>
                      <td className="p-2 font-bold text-emerald-700">
                        +{jb.downtimeSavedMinutes} mins
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Safety Checklist Signatures */}
          <div className="pt-6 border-t border-slate-200 grid grid-cols-3 gap-6 text-center text-[11px]">
            <div className="space-y-1">
              <div className="font-semibold text-slate-900">Er. A. K. Verma</div>
              <div className="text-slate-500">Chief Section Controller (COA)</div>
              <div className="text-[10px] text-emerald-700 font-bold">DIGITALLY SIGNED</div>
            </div>
            <div className="space-y-1">
              <div className="font-semibold text-slate-900">Er. R. S. Sharma</div>
              <div className="text-slate-500">Sr. Divisional Operations Manager</div>
              <div className="text-[10px] text-emerald-700 font-bold">APPROVED &amp; GAZETTED</div>
            </div>
            <div className="space-y-1">
              <div className="font-semibold text-slate-900">BlockSync AI Engine</div>
              <div className="text-slate-500">OR-Tools CP-SAT v9.8</div>
              <div className="text-[10px] text-slate-500 font-mono">100% FEASIBILITY CERTIFIED</div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-200 bg-slate-50 flex items-center justify-between">
          <span className="text-xs text-slate-500 font-mono">
            Official Document • Northern Railway Operating Circular 2026
          </span>
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-lg bg-slate-900 text-white hover:bg-slate-800 text-xs font-semibold cursor-pointer"
          >
            Close Bulletin
          </button>
        </div>
      </div>
    </div>
  );
};
